//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCalc.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuperCalc.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutMenuText {
            get {
                return ResourceManager.GetString("AboutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +.
        /// </summary>
        internal static string AddCommandText {
            get {
                return ResourceManager.GetString("AddCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to android=86137aef-d16e-409b-9555-f120442e365f;ios=fe6e1f90-2629-4930-b790-e118b75085ee.
        /// </summary>
        internal static string AppCenterMetricsKey {
            get {
                return ResourceManager.GetString("AppCenterMetricsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Calcular.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Button0 {
            get {
                return ResourceManager.GetString("Button0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Button1 {
            get {
                return ResourceManager.GetString("Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Button2 {
            get {
                return ResourceManager.GetString("Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Button3 {
            get {
                return ResourceManager.GetString("Button3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Button4 {
            get {
                return ResourceManager.GetString("Button4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Button5 {
            get {
                return ResourceManager.GetString("Button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Button6 {
            get {
                return ResourceManager.GetString("Button6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Button7 {
            get {
                return ResourceManager.GetString("Button7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Button8 {
            get {
                return ResourceManager.GetString("Button8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Button9 {
            get {
                return ResourceManager.GetString("Button9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot divide by Zero.
        /// </summary>
        internal static string CannotDivideByZeroErrorMessage {
            get {
                return ResourceManager.GetString("CannotDivideByZeroErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /.
        /// </summary>
        internal static string DivideCommandText {
            get {
                return ResourceManager.GetString("DivideCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        internal static string EqualsCommandText {
            get {
                return ResourceManager.GetString("EqualsCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x.
        /// </summary>
        internal static string MultiplyCommandText {
            get {
                return ResourceManager.GetString("MultiplyCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string NormalLayoutMenuText {
            get {
                return ResourceManager.GetString("NormalLayoutMenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -.
        /// </summary>
        internal static string SubtractCommandText {
            get {
                return ResourceManager.GetString("SubtractCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 Key.
        /// </summary>
        internal static string TenKeyLayoutMenuText {
            get {
                return ResourceManager.GetString("TenKeyLayoutMenuText", resourceCulture);
            }
        }
    }
}
